import 'package:flutter/material.dart';

enum AchievementCategory {
  constancy,
  volume,
  strength,
  intelligence,
}

class Achievement {
  final String id;
  final String title;
  final String description;
  final AchievementCategory category;
  final IconData icon;
  final double targetValue;
  final String unit;
  final int level;
  final String groupId;

  const Achievement({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.icon,
    this.targetValue = 1.0,
    this.unit = "",
    this.level = 0,
    this.groupId = "",
  });
}

// Catálogo base de logros
final List<Achievement> achievementsCatalog = [
  // NIVELES DE CONSTANCIA
  const Achievement(
    id: "first_workout",
    title: "Primer Paso (Nivel 1)",
    description: "Completaste tu primer entrenamiento.",
    category: AchievementCategory.constancy,
    icon: Icons.directions_run,
    targetValue: 1,
    unit: "entrs.",
    level: 1,
    groupId: "workouts",
  ),
  const Achievement(
    id: "workouts_l2",
    title: "Iniciado (Nivel 2)",
    description: "Completa 10 entrenamientos en total.",
    category: AchievementCategory.constancy,
    icon: Icons.shield,
    targetValue: 10,
    unit: "entrs.",
    level: 2,
    groupId: "workouts",
  ),
  const Achievement(
    id: "workouts_l3",
    title: "Guerrero de Cemento (Nivel 3)",
    description: "Completa 25 entrenamientos en total.",
    category: AchievementCategory.constancy,
    icon: Icons.shield,
    targetValue: 25,
    unit: "entrs.",
    level: 3,
    groupId: "workouts",
  ),
  const Achievement(
    id: "workouts_l4",
    title: "Atleta Experimentado (Nivel 4)",
    description: "Completa 50 entrenamientos en total.",
    category: AchievementCategory.constancy,
    icon: Icons.security,
    targetValue: 50,
    unit: "entrs.",
    level: 4,
    groupId: "workouts",
  ),
  const Achievement(
    id: "workouts_l5",
    title: "Centurión (Nivel 5)",
    description: "Alcanza los 100 entrenamientos completados.",
    category: AchievementCategory.constancy,
    icon: Icons.military_tech,
    targetValue: 100,
    unit: "entrs.",
    level: 5,
    groupId: "workouts",
  ),
  const Achievement(
    id: "workouts_l6",
    title: "Inmortal (Nivel 6)",
    description: "Alcanza los 150 entrenamientos completados. ¡Tu estilo de vida!",
    category: AchievementCategory.constancy,
    icon: Icons.diamond,
    targetValue: 150,
    unit: "entrs.",
    level: 6,
    groupId: "workouts",
  ),

  // EVENTOS DIARIOS CONSTANCIA
  const Achievement(
    id: "early_bird",
    title: "Madrugador",
    description: "Terminaste un entrenamiento antes de las 8:00 AM.",
    category: AchievementCategory.constancy,
    icon: Icons.wb_sunny,
  ),
  const Achievement(
    id: "night_owl",
    title: "Vampiro",
    description: "Terminaste un entrenamiento después de las 10:00 PM.",
    category: AchievementCategory.constancy,
    icon: Icons.nightlight_round,
  ),

  // NIVELES DE VOLUMEN DE SESIÓN
  const Achievement(
    id: "vol_session_l1",
    title: "Carretilla (Nivel 1)",
    description: "Mueve 2.000 kg en una sola sesión.",
    category: AchievementCategory.volume,
    icon: Icons.hardware,
    targetValue: 2000,
    unit: "kg",
    level: 1,
    groupId: "vol_session",
  ),
  const Achievement(
    id: "vol_session_l2",
    title: "Pick-up (Nivel 2)",
    description: "Mueve 4.000 kg en una sola sesión.",
    category: AchievementCategory.volume,
    icon: Icons.local_car_wash,
    targetValue: 4000,
    unit: "kg",
    level: 2,
    groupId: "vol_session",
  ),
  const Achievement(
    id: "vol_session_l3",
    title: "Camión Ligero (Nivel 3)",
    description: "Mueve 7.000 kg en una sola sesión.",
    category: AchievementCategory.volume,
    icon: Icons.fire_truck,
    targetValue: 7000,
    unit: "kg",
    level: 3,
    groupId: "vol_session",
  ),
  const Achievement(
    id: "vol_session_l4",
    title: "Montacargas Humano (Nivel 4)",
    description: "Supera los 9.000 kg levantados en una sola sesión.",
    category: AchievementCategory.volume,
    icon: Icons.precision_manufacturing,
    targetValue: 9000,
    unit: "kg",
    level: 4,
    groupId: "vol_session",
  ),
  const Achievement(
    id: "vol_session_l5",
    title: "Camión de Carga (Nivel 5)",
    description: "Mueve los 12.000 kg en una sola sesión.",
    category: AchievementCategory.volume,
    icon: Icons.local_shipping,
    targetValue: 12000,
    unit: "kg",
    level: 5,
    groupId: "vol_session",
  ),

  // NIVELES DE VOLUMEN TOTAL HISTÓRICO
  const Achievement(
    id: "total_vol_l1",
    title: "Vagón (Nivel 1)",
    description: "Acumula 20.000 kg levantados en tu historial.",
    category: AchievementCategory.volume,
    icon: Icons.inventory,
    targetValue: 20000,
    unit: "kg",
    level: 1,
    groupId: "total_vol",
  ),
  const Achievement(
    id: "total_vol_l2",
    title: "Zepelín (Nivel 2)",
    description: "Escala hasta los 50.000 kg en historial.",
    category: AchievementCategory.volume,
    icon: Icons.flight,
    targetValue: 50000,
    unit: "kg",
    level: 2,
    groupId: "total_vol",
  ),
  const Achievement(
    id: "total_vol_l3",
    title: "Locomotora (Nivel 3)",
    description: "Acumula 100.000 kg levantados en tu historial.",
    category: AchievementCategory.volume,
    icon: Icons.train,
    targetValue: 100000,
    unit: "kg",
    level: 3,
    groupId: "total_vol",
  ),
  const Achievement(
    id: "total_vol_l4",
    title: "Buque de Carga (Nivel 4)",
    description: "Alcanza los 150.000 kg de historial.",
    category: AchievementCategory.volume,
    icon: Icons.directions_boat,
    targetValue: 150000,
    unit: "kg",
    level: 4,
    groupId: "total_vol",
  ),
  const Achievement(
    id: "total_vol_l5",
    title: "El Monte Everest (Nivel 5)",
    description: "Llega a los épicos 200.000 kg a lo largo de tu cuenta.",
    category: AchievementCategory.volume,
    icon: Icons.terrain,
    targetValue: 200000,
    unit: "kg",
    level: 5,
    groupId: "total_vol",
  ),

  // INTELIGENCIA
  const Achievement(
    id: "rpe_maestro",
    title: "Francotirador del Esfuerzo",
    description: "Termina una sesión usando RPE sin llegar nunca al fallo (RPE 10).",
    category: AchievementCategory.intelligence,
    icon: Icons.my_location,
  ),
  const Achievement(
    id: "efficiency_master",
    title: "Eficiencia Pura",
    description: "Registra un entrenamiento con un bloque que tenga un RPE promedio bajo (<= 6) moviendo más de 2000 kg.",
    category: AchievementCategory.intelligence,
    icon: Icons.battery_charging_full,
  ),
  // NIVELES DE RACHA (CONSTANCIA)
  const Achievement(
    id: 'streak_l1',
    title: 'Chispa (Nivel 1)',
    description: 'Entrena 2 días seguidos.',
    category: AchievementCategory.constancy,
    icon: Icons.local_fire_department,
    targetValue: 2,
    unit: 'días',
    level: 1,
    groupId: 'streak',
  ),
  const Achievement(
    id: 'streak_l2',
    title: 'Llama (Nivel 2)',
    description: 'Consigue una racha de 3 días consecutivos.',
    category: AchievementCategory.constancy,
    icon: Icons.local_fire_department,
    targetValue: 3,
    unit: 'días',
    level: 2,
    groupId: 'streak',
  ),
  const Achievement(
    id: 'streak_l3',
    title: 'Fuego Vivo (Nivel 3)',
    description: 'Entrena 5 días seguidos sin fallar.',
    category: AchievementCategory.constancy,
    icon: Icons.whatshot,
    targetValue: 5,
    unit: 'días',
    level: 3,
    groupId: 'streak',
  ),
  const Achievement(
    id: 'streak_l4',
    title: 'Incendio (Nivel 4)',
    description: 'Alcanza una racha impresionante de 7 días.',
    category: AchievementCategory.constancy,
    icon: Icons.whatshot,
    targetValue: 7,
    unit: 'días',
    level: 4,
    groupId: 'streak',
  ),
  const Achievement(
    id: 'streak_l5',
    title: 'Inferno (Nivel 5)',
    description: 'Entrena 10 días consecutivos. Eres imparable.',
    category: AchievementCategory.constancy,
    icon: Icons.emergency,
    targetValue: 10,
    unit: 'días',
    level: 5,
    groupId: 'streak',
  ),

  // NIVELES DE SESIONES POR SEMANA (CONSTANCIA)
  const Achievement(
    id: 'weekly_l1',
    title: 'Constante (Nivel 1)',
    description: 'Completa al menos 2 sesiones en una misma semana.',
    category: AchievementCategory.constancy,
    icon: Icons.calendar_today,
    targetValue: 2,
    unit: 'ses./sem.',
    level: 1,
    groupId: 'weekly',
  ),
  const Achievement(
    id: 'weekly_l2',
    title: 'Rutinero (Nivel 2)',
    description: 'Completa 3 sesiones en una semana.',
    category: AchievementCategory.constancy,
    icon: Icons.calendar_month,
    targetValue: 3,
    unit: 'ses./sem.',
    level: 2,
    groupId: 'weekly',
  ),
  const Achievement(
    id: 'weekly_l3',
    title: 'Dedicado (Nivel 3)',
    description: 'Completa 4 sesiones en una sola semana.',
    category: AchievementCategory.constancy,
    icon: Icons.date_range,
    targetValue: 4,
    unit: 'ses./sem.',
    level: 3,
    groupId: 'weekly',
  ),
  const Achievement(
    id: 'weekly_l4',
    title: 'Atleta de Élite (Nivel 4)',
    description: 'Logra entrenar 5 veces en una misma semana.',
    category: AchievementCategory.constancy,
    icon: Icons.event_available,
    targetValue: 5,
    unit: 'ses./sem.',
    level: 4,
    groupId: 'weekly',
  ),
  const Achievement(
    id: 'weekly_l5',
    title: 'Semana Perfecta (Nivel 5)',
    description: '6 sesiones en una semana. Sin excusas.',
    category: AchievementCategory.constancy,
    icon: Icons.military_tech,
    targetValue: 6,
    unit: 'ses./sem.',
    level: 5,
    groupId: 'weekly',
  ),

  // NIVELES DE RPE PROMEDIO DE SESIÓN (INTELIGENCIA)
  const Achievement(
    id: 'avg_rpe_l1',
    title: 'Zona de Trabajo (Nivel 1)',
    description: 'Finaliza una sesión con un RPE promedio de al menos 6.5.',
    category: AchievementCategory.intelligence,
    icon: Icons.speed,
    targetValue: 6.5,
    unit: 'RPE',
    level: 1,
    groupId: 'avg_rpe',
  ),
  const Achievement(
    id: 'avg_rpe_l2',
    title: 'Alta Intensidad (Nivel 2)',
    description: 'Sesión con RPE promedio ≥ 7.0. Esfuerzo consistente y serio.',
    category: AchievementCategory.intelligence,
    icon: Icons.speed,
    targetValue: 7.0,
    unit: 'RPE',
    level: 2,
    groupId: 'avg_rpe',
  ),
  const Achievement(
    id: 'avg_rpe_l3',
    title: 'Límite Mental (Nivel 3)',
    description: 'Alcanza un RPE promedio de 7.5 en una sesión completa.',
    category: AchievementCategory.intelligence,
    icon: Icons.bolt,
    targetValue: 7.5,
    unit: 'RPE',
    level: 3,
    groupId: 'avg_rpe',
  ),
  const Achievement(
    id: 'avg_rpe_l4',
    title: 'Modo Bestia (Nivel 4)',
    description: 'RPE promedio ≥ 8.0 en toda la sesión. Ferozmente concentrado.',
    category: AchievementCategory.intelligence,
    icon: Icons.bolt,
    targetValue: 8.0,
    unit: 'RPE',
    level: 4,
    groupId: 'avg_rpe',
  ),
  const Achievement(
    id: 'avg_rpe_l5',
    title: 'Al Borde del Fallo (Nivel 5)',
    description: 'Sesión con RPE promedio ≥ 9.0. Entrenamiento de alto rendimiento máximo.',
    category: AchievementCategory.intelligence,
    icon: Icons.whatshot,
    targetValue: 9.0,
    unit: 'RPE',
    level: 5,
    groupId: 'avg_rpe',
  ),

  // NIVELES DE FATIGA MUSCULAR
  const Achievement(
    id: "fatigue_l1",
    title: "Sintiendo el Trabajo (Nivel 1)",
    description: "Lleva un grupo muscular al 35% de fatiga.",
    category: AchievementCategory.intelligence,
    icon: Icons.battery_4_bar,
    targetValue: 35,
    unit: "%",
    level: 1,
    groupId: "fatigue",
  ),
  const Achievement(
    id: "fatigue_l2",
    title: "Músculos Calientes (Nivel 2)",
    description: "Lleva un grupo muscular al 50% de fatiga.",
    category: AchievementCategory.intelligence,
    icon: Icons.battery_3_bar,
    targetValue: 50,
    unit: "%",
    level: 2,
    groupId: "fatigue",
  ),
  const Achievement(
    id: "fatigue_l3",
    title: "Zumbido Interno (Nivel 3)",
    description: "Lleva un grupo muscular al 70% de fatiga.",
    category: AchievementCategory.intelligence,
    icon: Icons.battery_2_bar,
    targetValue: 70,
    unit: "%",
    level: 3,
    groupId: "fatigue",
  ),
  const Achievement(
    id: "fatigue_l4",
    title: "Al Límite (Nivel 4)",
    description: "Lleva un grupo muscular al 85% de fatiga.",
    category: AchievementCategory.intelligence,
    icon: Icons.battery_1_bar,
    targetValue: 85,
    unit: "%",
    level: 4,
    groupId: "fatigue",
  ),
  const Achievement(
    id: "fatigue_l5",
    title: "Agotamiento Total (Nivel 5)",
    description: "Lleva un grupo muscular a su fatiga máxima (100%).",
    category: AchievementCategory.intelligence,
    icon: Icons.emergency,
    targetValue: 100,
    unit: "%",
    level: 5,
    groupId: "fatigue",
  ),

  // NIVELES DE FUERZA
  const Achievement(
    id: "strength_l1",
    title: "Fuerza Base (Nivel 1)",
    description: "Carga 60 kg en al menos una serie.",
    category: AchievementCategory.strength,
    icon: Icons.fitness_center,
    targetValue: 60,
    unit: "kg",
    level: 1,
    groupId: "strength",
  ),
  const Achievement(
    id: "heavy_lifter_session",
    title: "Levantador Pesado (Nivel 2)",
    description: "Carga 100 kg en al menos una serie.",
    category: AchievementCategory.strength,
    icon: Icons.fitness_center,
    targetValue: 100,
    unit: "kg",
    level: 2,
    groupId: "strength",
  ),
  const Achievement(
    id: "super_heavy_lifter",
    title: "Fuerza Descomunal",
    description: "Levanta 140 kg en al menos una serie.",
    category: AchievementCategory.strength,
    icon: Icons.monitor_weight,
    targetValue: 140,
    unit: "kg",
    level: 3,
    groupId: "strength",
  ),
  const Achievement(
    id: "titan_lifter",
    title: "Titán",
    description: "Levanta 180 kg en al menos una serie.",
    category: AchievementCategory.strength,
    icon: Icons.hardware,
    targetValue: 180,
    unit: "kg",
    level: 4,
    groupId: "strength",
  ),
  const Achievement(
    id: "elite_lifter",
    title: "Nivel Élite",
    description: "Alcanza los 220 kg en la barra. Estás en otro nivel.",
    category: AchievementCategory.strength,
    icon: Icons.diamond,
    targetValue: 220,
    unit: "kg",
    level: 5,
    groupId: "strength",
  ),
];