// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWWU5buvlFT25VjKbY2VUlA5VNlUGAoqM',
    appId: '1:525409951024:web:88f2662de4ae7f45833cf5',
    messagingSenderId: '525409951024',
    projectId: 'entrenamientoapplv',
    authDomain: 'entrenamientoapplv.firebaseapp.com',
    storageBucket: 'entrenamientoapplv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbsthTMkTMOBVUQ1yYC1SFW4sXvIx57I',
    appId: '1:525409951024:android:6bc88af46e8220eb833cf5',
    messagingSenderId: '525409951024',
    projectId: 'entrenamientoapplv',
    storageBucket: 'entrenamientoapplv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSsqwEIpt2EZhtO_Qb3o_5WyTj4ULwMQU',
    appId: '1:525409951024:ios:04b7f94c114d076e833cf5',
    messagingSenderId: '525409951024',
    projectId: 'entrenamientoapplv',
    storageBucket: 'entrenamientoapplv.firebasestorage.app',
    iosBundleId: 'com.example.entrenamientoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSsqwEIpt2EZhtO_Qb3o_5WyTj4ULwMQU',
    appId: '1:525409951024:ios:04b7f94c114d076e833cf5',
    messagingSenderId: '525409951024',
    projectId: 'entrenamientoapplv',
    storageBucket: 'entrenamientoapplv.firebasestorage.app',
    iosBundleId: 'com.example.entrenamientoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWWU5buvlFT25VjKbY2VUlA5VNlUGAoqM',
    appId: '1:525409951024:web:202ed6909004836a833cf5',
    messagingSenderId: '525409951024',
    projectId: 'entrenamientoapplv',
    authDomain: 'entrenamientoapplv.firebaseapp.com',
    storageBucket: 'entrenamientoapplv.firebasestorage.app',
  );
}
